### PR TITLE
#23 Parsing failures management

### PR DESCRIPTION
**Pull request by Whitehouse112**
- Added IParseFailureObserver interface that defines parsing errors handling methods. Methods deal with both syntax errors and duplicated/not found key/name errors for nodes, messages, signals and so on.

- Provided two implemetations for the interface:
   1 - SilentFailureObserver: does nothing, like today. It's the default observer
   2 - SimpleFailureObserver:  save each error in a list of string

- Added several tests for each parsing failure error

- Update Demo application to print errors, if any, using the SimpleFailureObserver class.

### CODE REVIEW

**Comment by EFeru** [comment]
Hi @Whitehouse112 , thanks for the effor in this PR. I am not sure if it is nomal, however if I run the Demo, I get ehe follwing warnings/failures:
image

**Comment by Whitehouse112** [comment]
Hi @EFeru,

- `[VAL_] Value table syntax error`: the [syntax specification](http://mcu.so/Microcontroller/Automotive/dbc-file-format-documentation_compress.pdf) implemented in this library doesn't support a signed integer as a valid value description for the VAL_ keyword. Syntax is `VAL_ var_name unsigned_integer char_string`. The reported lines contain a negative number, from which the syntax error
- `Unknown syntax error`: this is something I need to change, it regards the `NS_` definition at the beginning of the file. My though was to support only symbols actually implemented by the library itself but there is no reason to display this failures after all. I will fix asap.

Regards

**Comment by EFeru** [comment]
"Unknown syntax" is fixed. The following remained:
image

If I look in the [dbc file](https://github.com/EFeru/DbcParser/blob/main/DbcFiles/tesla_can.dbc) indeed I see negative values for `VAL_`, is this something not supported by this library or the dbc file is not according to dbc Vector specs?
image

**Comment by Whitehouse112** [comment]
- It's something not supported by this library? Yes
- It's not compliant to the dbc Vector spec? I don't know: the only [documentation](http://mcu.so/Microcontroller/Automotive/dbc-file-format-documentation_compress.pdf) available on the internet is the one provided also in this library and a signed integer is not a valid value for `VAL_` tag.

image

So this library supports only unsigned integer cause the only documentation available states that. This document is from 2010, I don't know if it has been updated, I looked for a recent version without success.

**Comment by Adhara3** [comment]
Hi,

It's very important that we find a reference and we stick with it. The document linked by @Whitehouse112 is by far the most complete and detailed resource we could find on the web.
Usually we also look for other software behaviour, we have the feeling that  the specs are a bit sloppy so software got quite tolerant on syntax over time.

How is CANdb++ behaving with those lines?

My 2 cents
A

**Comment by EFeru** [comment]
CANdb++ just adds the value description without complains.
image

**Pull request merged**
