### PR TITLE
Object oriented refactoring with unit tests

### PR DESCRIPTION
**Pull request by Adhara3**
Only basic tests have been added, more can be provided, especially on the pack/unpack part.
Two are failing because to me code does not meet expectations. If not, simply change tests accordingly.

### CODE REVIEW

**Comment by Adhara3** [comment]
Hi,

tomorrow I won-t be able to work on this, so I wanted to commit the current status even though this is **not** completed yet. 
I would like to add more unit tests on some line parsers. 

The reason I pushed is to allow you to see the result. If you completely disagree or dislike, I will just stop pushing and we can delete everything.
This new object oriented approach betters splits responsibilities IMHO and can be tested in a proper more detailed way. Being able to test single line parsers we can check for details, robustness on format etc... without having to test ful, dbc files.
At the end of the day, each `ILineParser` is responsible for a specific syntax parsing while `IDbcBuilder` is responsible for keeping internal links (e.g. current message or named tables). It scales, a new line syntax is just a new class.

The new structure already contains some fixes and supports more line syntaxes (of course those can be retrofitted to legacy code, if required).

Since the approach is quite different, I just would like you to see it and decide whether this is a suitable way to go.

Cheers
A

**Comment by EFeru** [comment]
This is really nice. Adding tests is something new for me in C#. I will be busy the next couple of days, still I hope I will find some time to look on it. I will also need to add automatic deployment to Nuget.
Please continue if your time allows.

**Comment by Adhara3** [comment]
> I will also need to add automatic deployment to Nuget.

Yes, we should also remove all binaries from the repository (at the moment in `.gitignore` you only remove `Debug` stuff)
I had an edit on this but I rolled back in order not to interfere with the deploy process. We'll tackle this aftewards

Cheers
A

**Comment by Adhara3** [comment]
To me this PR is complete.
You can add some more tests on the packer class if you wish.

Let me know

Cheers
A

**Comment by EFeru** [comment]
Hi @Adhara3,

I had a quick look at this PR. First of all I can see you have great programming skills, awesome work. I will need a bit of time to get familiar with the new way of handling things.

Then few of the comments I have:
1. I run the tests and I see 2 of them are failing. Seems it is on the old `DbcParser`. Do we want to keep these tests, what is your opinion?
image
2. Just out of curiosity, how did you derive the `regex` expressions, e.g., `private const string SignalRegex = @"\s*SG_\s+([\w]+)\s*([Mm\d]*)\s*:\s*(\d+)\|(\d+)@([01])([+-])\s+\(([\d\+\-eE.]+),([\d\+\-eE.]+)\)\s+\[([\d\+\-eE.]+)\|([\d\+\-eE.]+)\]\s+""(.*)""\s+([\w\s,]+)";`
3. In the `DbcBuilder` class I see methods like `AddSignal`, `AddMessage`, etc. Do you think is possible to parse a dbc, then add new or modify existing signals, and re-generate the `*.dbc` file? (just an idea, thinking out loud, I am not sure if it would be useful for something)
4. Can we update also the [Demo app](https://github.com/EFeru/DbcParser/tree/main/Demo)? Then we have a clear example on how to use the parser on a real application.
5. And if it is not too much hassle, can you update the ReadMe.md also with the new way?

**Comment by Adhara3** [comment]
Hi,

glad you like the result!

1. I left them red on purpose. They demonstrate that `DbcParser` has 2 bugs. (read twice does not clear and comments are not assigned correctly when multiple signals have the same name). What to do with tests depends on what you want to do with old class. If you want to keep it just for compatibility i.e. without any change or fix, you can either delete those tests, or change the assertions to make them green. Unit tests can be used as a live doc, so now the test is called `ParsingTwiceClearsCollectionTest` which describes the expectation (not met at the moment). If you rename the test like `ParsingTwiceIsDangerousBecauseNoClearIsPerformed` or `ParsingMultipleTimePilesMessagesIntheSameCollection` and change the expected count from 38 to 76, you get a green test that is also describing a (weird) behaviour. On the other hand  if you remove the class, of course the test does not compile anymore and can be removed.
2. I'm not sure I understand the question. I undestrand basic `regex` stuff and having a look at SG lines makes it quite obvious. I then use [this site](https://regex101.com/) to test them with several lines
3. The `DbcBuilder` class is at the moment meant for internal usage but, generally speaking, using a builder pattern like this allows to reverse input and output i.e. to rewrite the file. In this case we probably need another kind of builder because I would keep the line logic into the parsers, so the out builder is as simple as `builder.AddLine(string line)`. If you are interested in this, create an issue and we will tackle that once the refactoring is done
4. Yes, as soon as I understand if you want to keep or delete the legacy class
5. As point 4, otherwise in the `readme` I have to keep old methods too

Cheers
A

**Comment by EFeru** [comment]
Thanks for your reply.
- for now we can mark the old class `DbcParser` as obsolete (I will make a quick commit)
- in the next release I plan to remove it
- Regarding the tests, I think we can delete the tests for `DbcParser` completerly since we are going to remove it anyway. I am not sure if you are will to that
- And I would like that we update aleready the ReadMe and and Demo app for the new way of doing things, since the functionality will be there already with this PR

Then I want to add Github actions to:
- run the tests you made by github actions
- and push to NuGet everytime we create a tag/release

What do you think about these actions?

**Comment by Adhara3** [comment]
Hi,

done, I pushed the updates in `readme.md`, deleted `DbcParserTests.cs` and also the demo app is using the new parsing class.

I will be offline the rest of the week with no access to github, so I'll leave here a couple of thing I suggest to add before releasing.

1. Some more tests on `Packer`. I just wrote one, taking it from the `readme` example. You could add more, maybe using tricky or specific scenarios (both signed and unsigned, big and little endian, etc...) so that the they cover as many scenarios as possible
2. Add more _non regression tests_. Those are not real unit tests on classes, these are more end to end tests on the parsing process as a whole. We currently use a single file `tesla_can.dbc`, but it would be very useful to bring in all other dbc files from the same site and try to parse them all writing tests with assertions on number of nodes, messages and signals (bare minimum) and if possible checks on properties. With parsing lib the more the files we use the more the chances we find edge cases, errors or unsupported syntax.

Hope this helps
A

**Comment by EFeru** [comment]
1. Indeed is a good idea to add more tests
2. By "bring in all other dbc files from the same site" you mean to copy them in a separate folder in this repository or reference somewhow that repository?

**Comment by Adhara3** [comment]
> By "bring in all other dbc files from the same site" you mean to copy them in a separate folder in this repository or reference somewhow that repository?

There are pros and cons.
If you bring them in, and I would eventually place them in a dedicated test project subfolder, you are sure they will never change and being baselines for your tests that could help.

On the other hand, linking can work too but tests can become flaky if those file are continously updated.

I have no strong opinion, I would probably copy them to have a clear snapshot.
A

**Comment by EFeru** [comment]
I agree with copying the files. Do you see any issue with merging the CR?

**Comment by Adhara3** [comment]
Nope

**Comment by EFeru** [comment]
Merged. Awesome work @Adhara3 . Let's keep in contact on the open issues after your return. Thanks a lot!

**Comment by Adhara3** [comment]
You should also remove the bin/release folder from code and repo, if possible.
Fix the gitignore file accordingly.

A

**Comment by Adhara3** [comment]
Last thing. If you remove `DbcParser` class, remember to move `Message` and `Signal` classes into the Model subfolder, near the `Node` class.

A

**Pull request merged**
